app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

redis:
  addr: localhost:6379
  DB: 0
  Password: ""